title : Jonathan Tsai
tagline: this is pretty cool
author :
  name : Jonathan Tsai
  email : akajontsai-devel@yahoo.com
  github : jontsai
  twitter : jontsai
  feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
